#!/bin/sh

### BEGIN INIT INFO
# Provides:          grandalld
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: controls the grandalld url alias daemon
# Description:
#   Daemonize grandalld using start-stop-daemon from lib/lsd/init-functions.
#   Configuration and sites are stored 'globally' in /var/lib/grandall.
### END INIT INFO

. /lib/lsb/init-functions

GRANDALLD_CONFIG=/var/lib/grandall/grandalld.conf
GRANDALLD_SITES=/var/lib/grandall/sites-enabled

DAEMON_OPTS="-config $GRANDALLD_CONFIG -sites $GRANDALLD_SITES"
DAEMON=/usr/local/bin/grandalld
NAME=grandalld
DESC=grandalld

start_grandalld() {
	start-stop-daemon --start --quiet --background \
		--pidfile /var/run/$NAME.pid --make-pidfile \
		--exec $DAEMON -- $DAEMON_OPTS || true
}

stop_grandalld() {
	start-stop-daemon --stop --quiet \
		--pidfile /var/run/$NAME.pid \
		--exec $DAEMON -- $DAEMON_OPTS || true
}

case "$1" in
	start)
		echo -n "Starting $DESC: "
		start_grandalld
		echo "$NAME."
		;;

	stop)
		echo -n "Stopping $DESC: "
		stop_grandalld
		echo "$NAME."
		;;

	restart|force-reload|reload)
		echo -n "Restarting $DESC: "
		stop_grandalld
		sleep 1
		start_grandalld
		echo "$NAME."
		;;

	status)
		status_of_proc -p /var/run/$NAME.pid "$DAEMON" "$NAME" && exit 0 || exit $?
		;;
	*)
		echo "Usage: $NAME {start|stop|restart|reload|force-reload|status}" >&2
		exit 1
		;;
esac

exit 0
